name: Python package

on:
  release:
    types: ['published']


jobs:

  page_build:
    name: "Build documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r build_requirements.txt
          pip install -e .
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build docs
        run: |
          mkdocs build --verbose --clean --strict
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy_stage:
    name: 'Deploy release documentation'
    needs: page_build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      actions: read     # to download an artifact uploaded by `actions/upload-pages-artifact@v3`

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
